---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- local_action: stat path="{{ RC_PLAY_TOP }}/AWS/{{ AWS_Key_Name }}.pem"
  register: aws_key_file
  become: no

- include: create_ec2_key_pairs.yml
  when: not aws_key_file.stat.exists

- include: create_vpc.yml
  when: AWS_VPC == "none"

# Reload variables to catch changes
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: get_maskcidr.yml

- include: create_subnets.yml
  when: AWS_VPC_PRV_Subnet == "none"

# Reload variables to catch changes
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: create_routes.yml
  when: AWS_VPC_Routes == "none"

# Reload variables to catch changes
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: create_security_grp.yml
  when: AWS_VPC_Security_Group == "none"

# Reload variables to catch changes
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: create_nacls.yml
  when: AWS_VPC_NACLs == "none"
