---
# -----------------------------------
#  Copyright IBM Corp. 2021. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- include_vars: "{{ playbook_dir }}/GEN2/GEN2-config.yml"

- name: Create {{ role_path }}/files/ibmcloudgen2_templates.json
  file:
    path: "{{ role_path }}/files/ibmcloudgen2_templates.json"
    mode: '0644'
    state: touch

# The BEGIN/END ansible module marker will be replaced with {} in deploy-rc
- name: Modify {{ role_path }}/files/ibmcloudgen2_templates.json
  blockinfile:
    path: "{{ role_path }}/files/ibmcloudgen2_templates.json"
    block: |
        "templates": [
        {
            "templateId": "CENTOS-Template-NGVM-1",
            "maxNumber": {{ rc_maxNumber }},
            "attributes": {
                "type": ["String", "X86_64"],
                "ncores": ["Numeric", "{{ CORES_PER_SOCKET }}"],
                "ncpus": ["Numeric", "{{ SOCKET_PER_NODE }}"],
                "mem": ["Numeric", "{{ MEMORY_PER_NODE }}"],
                "icgen2host": ["Boolean", "1"]
            },
            "imageId": "{{ GEN2_Image_ID }}",
            "subnetId": "{{ GEN2_SUBNET_ID }}",
            "vpcId": "{{ GEN2_VPC_ID }}",
            "vmType": "{{ GEN2_PROFILE }}",
            "securityGroupIds": ["{{ GEN2_SG_ID }}"],
            "sshkey_id": "<lsf_key_id>",
            "region": "{{ GEN2_Region }}",
            "zone": "{{ GEN2_Zone }}"
        }
        ]

- name: Check if <lsf_key_id> in ibmcloudgen2_templates.json exists
  shell: grep "<lsf_key_id>" "{{ role_path }}/files/ibmcloudgen2_templates.json"
  changed_when: false
  register: key_update
  ignore_errors: yes

- when: not key_update.failed
  name: Get the {{ lsf_key_name }} key id on the cloud
  #shell: ibmcloud is keyc {{ lsf_key_name }}  @{{ role_path }}/files/id_rsa.pub --json | jq -r '.id'
  shell: ibmcloud is keys | grep {{ lsf_key_name }} | awk '{print $1}' | xargs ibmcloud is key -json | jq -r '.id'
  register: sshkey

- name: debug the ssh keyid
  debug:
    var: sshkey.stdout
  when: not key_update.failed

- name: replace <lsf_key_id>
  when: not key_update.failed
  replace:
    path: "{{ role_path }}/files/ibmcloudgen2_templates.json"
    regexp: "<lsf_key_id>"
    replace: "{{ sshkey.stdout }}"
    backup: no
