---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Check if necessary variables are defined
  fail:
    msg: "Need to specify {{item.key}} to run this step"
  when: item.key is undefined or item.val==""
  loop:
    - { key: tf_install_path, val: "{{tf_install_path|default(None)}}" }
    - { key: tf_owner, val: "{{tf_owner|default(None)}}" }
    - { key: tf_plugin_install_path, val: "{{tf_plugin_install_path|default(None)}}" }
    - { key: tf_plugin_owner, val: "{{tf_plugin_owner|default(None)}}" }

- name: "Create terraform/ under {{ tf_install_path }}"
  file:
    path: "{{ tf_install_path }}"
    state: directory
    owner: "{{tf_owner}}"
    mode: '0755'

- name: "Unarchive terraform {{ terraform_version }}"
  unarchive:
    src: "{{ terraform_url_path }}"
    dest: "{{ tf_install_path }}"
    creates: "{{ tf_install_path }}/terraform"
    remote_src: yes
    mode: "0755"


- name: "Create terraform plugin path under {{ tf_plugin_install_path }}"
  file:
    path: "{{ tf_plugin_install_path }}"
    state: directory
    owner: "{{tf_plugin_owner}}"
    mode: '0755'

- name: "Unarchive ibm cloud tf provider plugin {{ plugin_version }}"
  unarchive:
    src: "{{ plugin_url_path }}"
    dest: "{{ tf_plugin_install_path }}"
    creates: "{{ tf_plugin_install_path }}/terraform-provider-ibm_v{{ plugin_version }}"
    remote_src: yes
    owner: "{{tf_plugin_owner}}"
    mode: "0755"
