---
# -----------------------------------
#  Copyright IBM Corp. 2021. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- include_vars: "{{ playbook_dir }}/GEN2/GEN2-config.yml"

- name: Copy RC hostProviders config
  copy:
    src: "{{ playbook_dir }}/files/hostProviders.json"
    dest: "{{ LSF_CONF_DIR }}/resource_connector/hostProviders.json"
    mode: "0644"
    backup: yes
    owner: lsfadmin
    force: yes

- name: Create RC ibmcloudgen2 data dir
  file:
    path: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/data" 
    state: directory
    owner: lsfadmin
    mode: "0755"

- name: Copy RC ibmcloudgen2 template
  copy:
    src: "{{ playbook_dir }}/roles/prepare-files/files/ibmcloudgen2_templates.json"
    dest: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_templates.json"
    mode: "0644"
    backup: no
    owner: lsfadmin
    force: yes

- name: Copy RC ibmcloudgen2 config 
  copy:
    src: "{{ playbook_dir }}/roles/prepare-files/files/ibmcloudgen2_config.json"
    dest: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_config.json"
    mode: "0644"
    backup: no
    owner: lsfadmin
    force: yes

- name: Update RC ibmcloudgen2 template and config files (fix the BEGIN marker)
  replace:
    backup: no
    path: "{{ item }}"
    regexp: '# BEGIN ANSIBLE MANAGED BLOCK'
    replace: '{'
  loop:
    - "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_templates.json"
    - "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_config.json"

- name: Update RC ibmcloudgen2 template and config files (fix the END marker)
  replace:
    backup: no
    path: "{{ item }}"
    regexp: '# END ANSIBLE MANAGED BLOCK'
    replace: '}'
  loop:
    - "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_templates.json"
    - "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/conf/ibmcloudgen2_config.json"

- name: Copy RC ibmcloudgen2 user_data.sh
  copy:
    src: "{{ playbook_dir }}/roles/prepare-files/files/user_data.sh"
    dest: "{{ LSF_VER_DIR }}/resource_connector/ibmcloudgen2/scripts/user_data.sh"
    mode: "0755"
    backup: no
    owner: lsfadmin
    force: yes

- name: Copy RC ibmcloudgen2 ssh private key
  copy:
   src: "{{ ansible_env.HOME }}/.ssh/id_rsa"
   dest: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/data/id_rsa"
   mode: "0400"
   backup: no
   owner: lsfadmin
   force: yes
   remote_src: yes

- name: Create the credentials file
  file:
    path: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/data/credentials"
    state: touch
    mode: "0400"
    owner: lsfadmin
    force: yes

- name: Modify the credentials file
  blockinfile:
    path: "{{ LSF_CONF_DIR }}/resource_connector/ibmcloudgen2/data/credentials"
    block: |
      VPC_URL=http://vpc.cloud.ibm.com/v1
      VPC_AUTH_TYPE=iam
      VPC_APIKEY={{ lookup('env','IBMCLOUD_API_KEY') }}
      RESOURCE_RECORDS_URL=https://api.dns-svcs.cloud.ibm.com/v1
      RESOURCE_RECORDS_AUTH_TYPE=iam
      RESOURCE_RECORDS_APIKEY={{ lookup('env','IBMCLOUD_API_KEY') }}

