---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- hosts: tfhost
  tasks:
    - name: Check ansible version, need 2.7 for vars with include_tasks
      vars:
        req_major: 2
        req_minor: 7
      fail:
        msg: "Ansible version required: {{req_major}}.{{req_minor}}, detected: {{ansible_version.full}}"
      when: ansible_version is undefined or ansible_version.major < req_major or ansible_version.minor < req_minor


    - include_tasks: "roles/common/tasks/get_files_dir.yml"
      when: gen_files_dir is undefined

    - import_role:
        name: check-api-key
      tags:
        - always

    # optional steps, need explicit tags to be run
    - import_role:
        name: install-ibmcloud-cli
      vars:
        GEN2_region: "{{ vpc_region }}"
      tags:
        - never
        - install-ibmcloud-cli
        - prereq

    # optional steps, need explicit tags to be run
    - import_role:
        name: install-terraform
      vars:
        tf_install_path: "{{tfbinary_path}}"
        tf_owner: "{{tfuser|default(ansible_user_id)}}"
        tf_plugin_install_path: "{{tfplugin_path}}"
        tf_plugin_owner: "{{tfuser|default(ansible_user_id)}}"
      tags:
        - never
        - install-terraform
        - prereq


    # make role run only if no installation step ran
    - set_fact:
        no_install: true
      tags:
        - never
        - install-terraform
        - install-ibmcloud-cli
        - prereq
      no_log: yes

    - import_role:
        name: create_vpc
      when: no_install is undefined and no_install == false
