---
# -----------------------------------
#  Copyright IBM Corp. 1992, 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Construct a list of master and worker hostnames
  set_fact:
    master_list: "{{ groups['master'] | map('extract', hostvars, ['ansible_hostname']) | join('\n') }}"
    worker_list: "{{ groups['worker'] | map('extract', hostvars, ['ansible_hostname']) | join('\n') }}"
    deployer: "{{ ansible_hostname }}"

- name: Send the lsf-inventory to the deployer
  template:
    src: lsf-inventory.j2
    dest: /opt/ibm/lsf_installer/playbook/lsf-inventory
    force: yes

- name: Set the LSF cluster name
  lineinfile:
    path: /opt/ibm/lsf_installer/playbook/lsf-config.yml
    regexp: 'my_cluster_name'
    line: "  my_cluster_name: {{ lsf_cluster_name }}"
    state: present
    backup: yes

- name: Set the LSF NFS install dir
  lineinfile:
    path: /opt/ibm/lsf_installer/playbook/lsf-config.yml
    regexp: '  NFS_install_dir: '
    line: "  NFS_install_dir: {{ nfs_mnt_dir }}"
    state: present
    backup: yes

- name: Set the USE_TCP variable in the installer group_vars to prevent UDP fragmentation issues
  lineinfile:
    path: /opt/ibm/lsf_installer/playbook/group_vars/all
    line: "USE_TCP: true"

- name: Replace the configure_conf_files.yml to the version that respects USE_TCP
  copy:
    src: "configure_conf_files.yml"
    dest: /opt/ibm/lsf_installer/playbook/roles/lsf-common/tasks/configure_conf_files.yml
