#
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------
#
---

- name: Provision the EC2 node that will be VPN and maybe LSF server
  ec2:
    aws_access_key: "{{ AWS_Access_Key }}"
    aws_secret_key: "{{ AWS_Secret_Key }}"
    key_name: "{{ AWS_Key_Name }}"
    group_id: "{{ AWS_VPC_Security_Group }}"
    ec2_url: "{{ AWS_EC2_URL }}"
    instance_type: "{{ AWS_Instance_Type }}"
    region: "{{ AWS_Region }}"
    image: "{{ AWS_Image }}"
    vpc_subnet_id: "{{ AWS_VPC_PRV_Subnet }}"
    assign_public_ip: yes
    source_dest_check: no
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ AWS_Root_Disk_Size }}"
        delete_on_termination: yes
    wait: true
    exact_count: 1
    count_tag: foo
    instance_tags:
      Name: VPN-host-SC
  register: ec2_SC

