---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------


- set_fact:
    api_key: "{{ lookup('env','IBMCLOUD_API_KEY') | default(None) }}"

- name: Check if the IBMCLOUD_API_KEY env. variable is defined
  fail:
    msg: "Exit when IBMCLOUD_API_KEY is not defined or is empty on the playbook host."
  when: api_key == ''
