---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- include_tasks: "../../common/tasks/get_files_dir.yml"
  when: gen_files_dir is undefined or gen_files_dir == ""

- name: Retrieve VPN GW info from file
  vars:
    vpn_file: "{{gen_files_dir}}/vpn.yml"
  set_fact:
    vpn_cn: "{{ lookup('file', vpn_file) | from_yaml }}"

###################################
  # done in script, later can be done here
# - name: "Enable epel-release"
#   yum:
#     name: epel-release
#     state: latest
#   become: yes

# - name: "Install openvpn packages"
#   yum:
#     update_cache: yes
#     name: [openvpn easy-rsa]
#     state: latest
#   become: yes
###################################
- name: "Create scripts directory"
  file:
    path: "{{gen_files_dir}}/scripts"
    state: directory

- name: "Template the setup script"
  vars:
    setup_type: "master"
    purge: 1
  template:
    src: "../../open_vpn/templates/vpn_setup.sh.j2"
    dest: "{{gen_files_dir}}/scripts/setup.sh"
    mode: u=rwx,go=rx

- name: "Upload remaining scripts"
  copy:
    src: "../../open_vpn/files/{{item}}"
    dest: "{{gen_files_dir}}/scripts/{{item}}"
    mode: preserve
  loop:
    - vpn_functions.sh
    - logging_functions.sh
    - setup-server.sh
    - setup-client.sh

- name: "Run setup script"
  command:
    argv:
      - "./setup.sh"
    chdir: "{{gen_files_dir}}/scripts"
  become: yes
