---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: "Check and Read env variable: GEN_FILES_DIR"
  vars:
    def_dir: ""
    usr_dir: "{{ lookup('env', 'GEN_FILES_DIR') | default('')}}"
    detected_path: "{{ def_dir if usr_dir == '' else usr_dir }}"
  set_fact:
    gen_files_dir: "{{ detected_path|regex_replace('(.*)[/]$','\\1') }}"
  when: gen_files_dir is undefined or gen_files_dir|length == 0

- fail:
    msg: "GEN_FILES_DIR environment variable is not set. Please point to a directory with/for generated files"
  when: gen_files_dir is undefined or gen_files_dir == ""

- debug:
    msg: "Directory for generated files is: {{gen_files_dir}}"
