---
# -----------------------------------
#  Copyright IBM Corp. 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------


- fail:
    msg: "target_region variable needs to be defined"
  when: target_region is undefined

- name: Get current region info
  command:
    argv:
      - ibmcloud
      - target
      - -output
      - JSON
  register: target_output

- set_fact:
    current_region: "{{ target_output.stdout | from_json }}"

- name: Make sure to target the correct region
  command:
    argv:
      - ibmcloud
      - target
      - -r
      - "{{target_region}}"
  when: current_region.region.name != target_region
