---

# -----------------------------------
#  Copyright IBM Corp. 1992, 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- include_tasks: "../../common/tasks/get_files_dir.yml"
  when: gen_files_dir is undefined or gen_files_dir == ""

- name: Copy the generated authentication files to the Cloud machine
  copy:
    src: "{{ gen_files_dir }}/etc/{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
  with_items:
    - { src: 'passwd', dest: 'passwd.append' }
    - { src: 'group',  dest: 'group.append' }
    - { src: 'shadow', dest: 'shadow.append' }
    - { src: 'hosts',  dest: 'hosts.append' }
  become: yes

- name: Update the authentication files
  shell: cat "{{ item.src }}" >> "{{ item.dest }}"
  args:
    warn: False
    chdir: /etc
    creates: /etc/.passwd.updated
  with_items:
    - { src: 'passwd.append', dest: 'passwd' }
    - { src: 'group.append',  dest: 'group' }
    - { src: 'shadow.append', dest: 'shadow' }
    - { src: 'hosts.append',  dest: 'hosts' }
    - { src: 'passwd.append', dest: '.passwd.updated' }
  become: yes

- name: create base home dir in shared FS
  file:
    path: "{{ nfs_mnt_dir }}/home"
    state: directory
    owner: root
    group: root
    mode: ugo+rx
  become: yes

- name: change/update user home directory setting
  user:
    name: "{{item}}"
    home: "{{nfs_mnt_dir}}/home/{{item}}"
    generate_ssh_key: yes
  loop: "{{multicluster.lsf_user_list}}"
  become: yes

- name: Authorize cloud-side ssh keys
  command:
    argv:
      - cp
      - "{{nfs_mnt_dir}}/home/{{item}}/.ssh/id_rsa.pub"
      - "{{nfs_mnt_dir}}/home/{{item}}/.ssh/authorized_keys"
    creates: "{{nfs_mnt_dir}}/home/{{item}}/.ssh/authorized_keys"
  loop: "{{multicluster.lsf_user_list}}"
  become: yes

- name: Check/correct permissions on authorized_key file
  file:
    path: "{{nfs_mnt_dir}}/home/{{item}}/.ssh/authorized_keys"
    owner: "{{item}}"
    mode: u=rw,go=r
  loop: "{{multicluster.lsf_user_list}}"
  become: yes
