---
# -----------------------------------
#  Copyright IBM Corp. 2021. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- hosts: LSF_Masters[0]
  tasks:
  - name: fetch the public key from the LSF master
    fetch:
      src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
      dest: "{{ playbook_dir }}/files/"
      flat: yes

- hosts: local
  tasks:
  - include_vars: "{{ playbook_dir }}/GEN2/GEN2-config.yml"
  - name: generate a new key {{ lsf_key_name }} on the cloud
    shell: ibmcloud is keyc {{ lsf_key_name }}  @{{ playbook_dir }}/files/id_rsa.pub

