---
# -----------------------------------
#  Copyright IBM Corp. 2021. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Check if the IBMCLOUD_API_KEY env. variable is defined
  hosts: local
  vars:
    api_key: "{{ lookup('env','IBMCLOUD_API_KEY') }}"

  tasks:
  - fail:
      msg: "Exit when IBMCLOUD_API_KEY is not defined on the local host."
    when: api_key == ''

- name: Install tools (terraform, ibm cloud terraform plugin, etc)
  hosts: LSF_Masters
  roles:
    - deploy-rc-gen2-plugin
