---
# -----------------------------------
#  Copyright IBM Corp. 1992, 2018. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Copy files to Cloud and merge
  debug:
    msg: "Start..."

- name: Copy the generated files to the Cloud machine
  copy:
    src: "{{ RC_PLAY_TOP }}/files/{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
  with_items:
    - { src: 'passwd', dest: 'passwd.append' }
    - { src: 'group',  dest: 'group.append' }
    - { src: 'shadow', dest: 'shadow.append' }
    - { src: 'hosts',  dest: 'hosts.append' }

- name: Update the authentication files
  shell: cat "{{ item.src }}" >> "{{ item.dest }}"
  args:
    warn: False
    chdir: /etc
    creates: /etc/.passwd.updated
  with_items:
    - { src: 'passwd.append', dest: 'passwd' }
    - { src: 'group.append',  dest: 'group' }
    - { src: 'shadow.append', dest: 'shadow' }
    - { src: 'hosts.append',  dest: 'hosts' }
    - { src: 'passwd.append', dest: '.passwd.updated' } 

- name: Finished Updating Authentication files from the Deployer
  debug:
    msg: "Done..."
