---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: make-role.yml
  when:
    - multi_cluster is defined
    - multi_cluster == true
    - AWS_IAM_Role_Name == "none"
