---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

# Read variables for subnets
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

# The LSF master will have the client side VPN
- include: setup-client-vpn.yml
