---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- name: Key directory
  file:
    path: "/etc/openvpn/keys"
    recurse: yes
    state: directory

- name: Copy VPN client myvpn.tlsauth
  copy:
    src: "{{ RC_PLAY_TOP }}/VPN/myvpn.tlsauth"
    dest: /etc/openvpn/myvpn.tlsauth
    mode: 0400

- name: Copy VPN client ca.crt
  copy:
    src: "{{ RC_PLAY_TOP }}/VPN/ca.crt"
    dest: /etc/openvpn/keys/ca.crt

- name: Copy VPN client client.key
  copy:
    src: "{{ RC_PLAY_TOP }}/VPN/client.key"
    dest: /etc/openvpn/keys/client.key
    mode: 0400

- name: Copy VPN client client.crt
  copy:
    src: "{{ RC_PLAY_TOP }}/VPN/client.crt"
    dest: /etc/openvpn/keys/client.crt

- name: Copy VPN client client.ovpn
  copy:
    src: "{{ RC_PLAY_TOP }}/VPN/client.ovpn"
    dest: /etc/openvpn/client.conf

- name: Update Client configuration file
  lineinfile:
    dest: /etc/openvpn/client.conf
    backrefs: yes
    regexp: '^(remote).*'
    line: '\1 {{ ec2.instances[0].public_ip }} 1194 udp'

- name: Enable IP forwarding
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  args:
    warn: False

#- name: Enable TUN interface forwarding
#  shell: "{{ item }}"
#  args:
#    warn: False
#  with_items:
#    - iptables -A INPUT -i tun+ -j ACCEPT
#    - iptables -A FORWARD -i tun+ -j ACCEPT

- name: Enable TUN interface input
  iptables:
    action: insert
    chain: INPUT
    in_interface: tun+
    jump: ACCEPT

- name: Enable TUN interface forwarding
  iptables:
    action: insert
    chain: FORWARD
    in_interface: tun+
    jump: ACCEPT

- name: Start the VP Client
  systemd:
    name: openvpn@client.service
    state: restarted
    enabled: True
    daemon_reload: yes

- name: -----  WARNING   Iptables have been modified!!!!!!!!
  debug:
    msg: "NOTE:  Iptables has been modified to allow VPN subnet access!!!!"

