---
# -----------------------------------
#  Copyright IBM Corp. 1992,2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Make sure nfs-utils are installed
  vars:
    pkg_list:
      - nfs-utils
  yum:
    name: "{{ pkg_list }}"
    state: installed
    update_cache: yes

- name: Create mount point
  file:
    path: "{{ nfs_mnt_dir }}"
    state: directory
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root

- name: Mount NFS export
  mount:
    name: "{{ nfs_mnt_dir }}"
    src: "{{ nfs_server_ip }}:{{ nfs_mnt_dir }}"
    fstype: nfs
    opts: "_netdev,noac,rsize=1048576,wsize=1048576"
    backup: no
    boot: no
    state: mounted
  when: inventory_hostname != hostvars[ groups['deployer'][0]]['inventory_hostname']
