---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------
# 

- name: Changing clustername
  debug:
    msg: "Changing from myCluster to {{ CLOUD_LSF_CLUSTER_NAME }}"

- name: Change the cluster name in conf files
  script: "../files/change_clustername.sh -c {{ CLOUD_LSF_CLUSTER_NAME }}"
  args:
    creates: "{{ LSF_CONF_DIR }}/.clustername.{{ CLOUD_LSF_CLUSTER_NAME }}.changed"

