---
# -----------------------------------
#  Copyright IBM Corp. 2021. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- include_vars: "{{ playbook_dir }}/GEN2/GEN2-config.yml"

#--lsf.conf
################################################################################
- name: Update LSF lsf.conf add LSB_RC_EXTERNAL_HOST_FLAG 
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "LSB_RC_EXTERNAL_HOST_FLAG=icgen2host"

- name: Update LSF lsf.conf add LSB_RC_EXTERNAL_HOST_IDLE_TIME
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "LSB_RC_EXTERNAL_HOST_IDLE_TIME=5"

- name: Update LSF lsf.conf add LSF_DYNAMIC_HOST_TIMEOUT
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "LSF_DYNAMIC_HOST_TIMEOUT=25m"

- name: Update LSF lsf.conf add LSF_DYNAMIC_HOST_WAIT_TIME
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "LSF_DYNAMIC_HOST_WAIT_TIME=2"

- name: Update LSF lsf.conf add ENABLE_DYNAMIC_HOSTS
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "ENABLE_DYNAMIC_HOSTS=Y"

- name: Update LSF lsf.conf add LSB_CALL_LIM_RETRY
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    state: present
    line: "LSB_CALL_LIM_RETRY=3"

- name: Update LSF lsf.conf to disable EGO with LSF_ENABLE_EGO=N
  lineinfile:
    path: "{{ LSF_CONF_DIR }}/lsf.conf"
    regexp: '^LSF_ENABLE_EGO=Y' 
    line: "LSF_ENABLE_EGO=N"

- name: Update LSF lsf.conf to set LSF_ANNOUNCE_MASTER_TCP_WAITTIME=15 
  lineinfile:
    path: "{{ LSF_CONF_DIR }}/lsf.conf"
    regexp: '^LSF_ANNOUNCE_MASTER_TCP_WAITTIME=0' 
    line: "LSF_ANNOUNCE_MASTER_TCP_WAITTIME=15"

#--lsf.cluster
################################################################################
 
- name: Update LSF cluster file - lsf.cluster.{{ LSF_CLUSTER_NAME }}
  lineinfile:
    path: "{{ LSF_CONF_DIR }}/lsf.cluster.{{ LSF_CLUSTER_NAME }}"
    backup: yes
    insertafter: 'Begin Parameters'
    line:  LSF_HOST_ADDR_RANGE=*.*.*.*

#--lsf.shared
################################################################################
- name: Update lsf.shared
  lineinfile:
    path: "{{ LSF_CONF_DIR }}/lsf.shared"
    backup: yes
    insertafter: awshost
    line: '   icgen2host Boolean ()       ()          (GEN2 Hosts borrowed from IBM Cloud)'

- name: Uncomment the instanceID so we can use it
  replace:
    backup: yes             
    path: "{{ LSF_CONF_DIR }}/lsf.shared" 
    regexp: '^#(.*instanceID.*)'
    replace: '\1'

#--lsb.modules
################################################################################
- name: Update the lsb.modules file - Uncomment schmod_demand
  replace:
    backup: yes             
    path: "{{ LSF_CONF_DIR }}/lsbatch/{{ LSF_CLUSTER_NAME }}/configdir/lsb.modules"
    regexp: '^#(.*schmod_demand.*)'
    replace: '\1'

#--lsb.queue
################################################################################
- name: Update the lsb.queue file
  lineinfile:
    path: "{{ LSF_CONF_DIR }}/lsbatch/{{ LSF_CLUSTER_NAME }}/configdir/lsb.queues"
    backup: yes
    insertafter: .*QUEUE_NAME.*normal.*
    line: RC_HOSTS     = icgen2host

################################################################################
- name: Add lsfadmin to the sudo group
  shell: usermod -aG wheel lsfadmin

- name: Allow nopasswd for sudo lsfadmin
  lineinfile:
    path: /etc/sudoers
    state: present 
    backup: yes
    line: 'lsfadmin ALL = NOPASSWD : ALL'
    validate: '/usr/sbin/visudo -cf %s'

# May need to restart mbd on multiple masters?
#- name: Finally restart mbatchd/ebrokerd on Master
#  shell: lsadmin reconfig && lsadmin limrestart && badmin reconfig && badmin mbdrestart

#- name: restart lsfd
#    service: name=lsfd state=restarted
