---
# -----------------------------------
#  Copyright IBM Corp. 1992, 2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- fail:
    msg: "missing variable definition: {{item}}"
  when: vars[item] is undefined
  loop:
    - LSF_CONF_DIR
    - CLOUD_LSF_CLUSTER_NAME
    - LOCAL_LSF_CLUSTER_NAME
    - cloud_master
    - onprem_master
    - RC_HOSTS_NAME

- debug:
    msg: "variable definition: {{item.k}}: {{item.v}}"
  loop:
    - { k: "LSF_CONF_DIR",           v: "{{LSF_CONF_DIR}}" }
    - { k: "CLOUD_LSF_CLUSTER_NAME", v: "{{CLOUD_LSF_CLUSTER_NAME}}" }
    - { k: "LOCAL_LSF_CLUSTER_NAME", v: "{{LOCAL_LSF_CLUSTER_NAME}}" }
    - { k: "cloud_master",           v: "{{cloud_master}}" }
    - { k: "onprem_master",          v: "{{onprem_master}}" }
    - { k: "RC_HOSTS_NAME",          v: "{{RC_HOSTS_NAME}}" }


# modify the LSF lsf.shared file
- name: Update lsf.shared to add Servers
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.shared"
    backrefs: yes
    state: present
    regexp: '^ClusterName.*'
    line: 'ClusterName     Servers                 # Keyword'
    backup: yes
  notify: restart lsf

- name: Update on-cloud cluster info with master host name into lsf.shared
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.shared"
    state: present
    backup: yes
    regexp: "^{{ CLOUD_LSF_CLUSTER_NAME | default('myCloudCluster') }}.*"
    line: '{{ CLOUD_LSF_CLUSTER_NAME | default("myCloudCluster") }} {{ cloud_master }}'
  notify: restart lsf

- name: Append on-premise cluster info to lsf.shared
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.shared"
    state: present
    insertbefore: "^End Cluster.*"
    line: '{{ LOCAL_LSF_CLUSTER_NAME }}        {{ onprem_master }}'
    backup: yes
  notify: restart lsf

- name: Update LSF cluster file
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.cluster.{{ CLOUD_LSF_CLUSTER_NAME | default('myCloudCluster') }}"
    state: present
    insertafter: "^Begin Parameters.*"
    backup: yes
    line: "PRODUCTS=LSF_Make LSF_Base LSF_Manager LSF_MultiCluster"
  notify: restart lsf

#update lsb.queue to add receive request queue
- name: Update the lsb.queue file
  blockinfile:
    dest: "{{ LSF_CONF_DIR }}/lsbatch/{{ CLOUD_LSF_CLUSTER_NAME | default('myCloudCluster') }}/configdir/lsb.queues"
    backup: yes
    block: |
      Begin Queue
      QUEUE_NAME    = recOnprem
      PRIORITY      = 40
      RCVJOBS_FROM  = {{ LOCAL_LSF_CLUSTER_NAME }}
      RC_HOSTS      = {{ RC_HOSTS_NAME }}
      DESCRIPTION   = Sample Queue for receving onprem cluster request
      End Queue
  notify: restart lsf

- name: Update lsf.conf (Disable DYNAMIC HOSTS)
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.conf"
    backrefs: yes
    regexp: '^(ENABLE_DYNAMIC_HOSTS.*)'
    line: '# \1'
    backup: yes
  notify: restart lsf

- name: Update LSF cluster file
  lineinfile:
    dest: "{{ LSF_CONF_DIR }}/lsf.cluster.{{ CLOUD_LSF_CLUSTER_NAME | default('myCloudCluster') }}"
    state: present
    insertbefore: "^End Parameters.*"
    backup: yes
    line: "LSF_HOST_ADDR_RANGE=*.*.*.*"
  notify: restart lsf
