---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- name: Check for existing authorized_keys
  stat:
    path: /root/authorized_keys
  register: have_authorized_keys

- name: Copy ssh key from deployer
  copy:
    src: files/id_rsa.pub
    dest: /root/authorized_keys
  when: have_authorized_keys.stat.exists == False

- name: Update Authoried Keys
  shell: cat /root/authorized_keys >> /root/.ssh/authorized_keys
  when: have_authorized_keys.stat.exists == False

