---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

# Load AWS variables
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: config-lsf-server.yml
  when: 
    - multi_cluster is defined
    - multi_cluster == true

- include: setup-lsf-server.yml

- include: setup-lsf-postreqs.yml
  when: 
    - hybrid_cluster is defined
    - hybrid_cluster == true
    
- include: restart-lsf.yml
