---
# -----------------------------------
#  Copyright IBM Corp. 1992,2020. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- stat:
    path: "{{nfs_mnt_dir}}/.mounted"
  register: mnt_fstat


- block:
    - name: Check device that has the requested size
      shell: lsblk -d --output NAME,SIZE | grep "{{ nfs_volume_size }}" | tail -n 1 | awk '{print $1}'
      register: available_disk

    - name: lsblk debug print
      debug:
        msg: "{{ available_disk.stdout }}"

    - name: Create a file system
      filesystem:
        fstype: ext4
        dev: "/dev/{{ available_disk.stdout }}"
        force: no

    - name: Mount block storage
      mount:
        path: "{{ nfs_mnt_dir }}"
        src: "/dev/{{ available_disk.stdout }}"
        state: mounted
        fstype: ext4

  when: mnt_fstat.stat.exists == False


- name: Make sure nfs-utils are installed
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
    - nfs-utils

- name: update /etc/exports
  lineinfile:
    path: /etc/exports
    regexp: "{{ nfs_mnt_dir }}"
    line: "{{ nfs_mnt_dir }} *(rw,sync,no_root_squash)"

- name: update /etc/sysconfig/nfs
  lineinfile:
    path: /etc/sysconfig/nfs
    regexp: '^.*RPCNFSDCOUNT.*'
    line: RPCNFSDCOUNT=32

- name: restart nfs server
  service: name=nfs-server state=restarted
